"""
This type stub file was generated by pyright.
"""

from smolagents import Model

leopard_prompt = ...
def parse_arguments(): # -> Namespace:
    ...

def load_model(model_type: str, model_id: str, api_base: str | None = ..., api_key: str | None = ..., provider: str | None = ...) -> Model:
    ...

def run_smolagent(prompt: str, tools: list[str], model_type: str, model_id: str, api_base: str | None = ..., api_key: str | None = ..., imports: list[str] | None = ..., provider: str | None = ...) -> None:
    ...

def main() -> None:
    ...

if __name__ == "__main__":
    ...
