"""
This type stub file was generated by pyright.
"""

from smolagents import CodeAgent, tool
from smolagents.agents import ActionStep

github_request = ...
search_request = ...
def parse_arguments(): # -> Namespace:
    ...

def save_screenshot(memory_step: ActionStep, agent: CodeAgent) -> None:
    ...

@tool
def search_item_ctrl_f(text: str, nth_result: int = ...) -> str:
    """
    Searches for text on the current page via Ctrl + F and jumps to the nth occurrence.
    Args:
        text: The text to search for
        nth_result: Which occurrence to jump to (default: 1)
    """
    ...

@tool
def go_back() -> None:
    """Goes back to previous page."""
    ...

@tool
def close_popups() -> str:
    """
    Closes any visible modal or pop-up on the page. Use this to dismiss pop-up windows! This does not work on cookie consent banners.
    """
    ...

def initialize_driver():
    """Initialize the Selenium WebDriver."""
    ...

def initialize_agent(model): # -> CodeAgent:
    """Initialize the CodeAgent with the specified model."""
    ...

helium_instructions = ...
def run_webagent(prompt: str, model_type: str, model_id: str, provider: str | None = ..., api_base: str | None = ..., api_key: str | None = ...) -> None:
    ...

def main() -> None:
    ...

if __name__ == "__main__":
    ...
